version: "3.5"

services:

  jenkins:
    image: jenkinsci/blueocean
    user: "root"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data/.m2:/var/jenkins_home/.m2/repository
    ports:
      - "8085:8080"
    networks:
      - devops

networks:
  devops:
    name: devops
    driver: bridge
